BEGIN {
 A[0]="[turbomed]"; P[0]="/opt/turbomed"; avail[0]=1;
 A[1]="[php]"; P[1]="/srv/www/htdocs"; avail[1]=1;
 A[2]="[efi]"; P[2]="/boot/efi"; avail[2]=0;
 A[3]="[diabfb]"; P[3]="/mnt/diabfb"; avail[3]=0;
 A[4]="[obslaeuft]"; P[4]="/obslaeuft"; avail[4]=0;
 A[5]="[daten]"; P[5]="/DATA"; avail[5]=0;
 A[6]="[virtwinturbomed]"; P[6]="/mnt/virtwin/turbomed"; avail[6]=0;
 A[7]="[virtwin0turbomed]"; P[7]="/mnt/virtwin0/turbomed"; avail[7]=0;
 A[8]="[virtwin7turbomed]"; P[8]="/mnt/virtwin7/turbomed"; avail[8]=0;
 A[9]="[virtwin8turbomed]"; P[9]="/mnt/virtwin8/turbomed"; avail[9]=0;
 A[10]="[win1]"; P[10]="/win1"; avail[10]=0;
};
