BEGIN {
 A[0]="[turbomed]"; P[0]="/opt/turbomed"; avail[0]=1;
 A[1]="[php]"; P[1]="/srv/www/htdocs"; avail[1]=1;
 A[2]="[efi]"; P[2]="/boot/efi"; avail[2]=0;
 A[3]="[diabfb]"; P[3]="/mnt/diabfb"; avail[3]=0;
 A[4]="[SeagateBackupPlusDrive]"; P[4]="/mnt/SeagateBackupPlusDrive"; avail[4]=0;
 A[5]="[daten]"; P[5]="/DATA"; avail[5]=0;
 A[6]="[root]"; P[6]="/mnt/root"; avail[6]=0;
 A[7]="[OPENSUSE-LE]"; P[7]="/mnt/OPENSUSE-LE"; avail[7]=0;
 A[8]="[win1]"; P[8]="/win1"; avail[8]=0;
 A[9]="[DAT2]"; P[9]="/DAT2"; avail[9]=0;
};
